name: my_marvel
description: My Marvel is a project that consumes the Marvel API https://developer.marvel.com/.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  dartz: ^0.10.1
  http: ^0.13.4
  flutter_bloc: ^8.0.1
  provider: ^6.0.2
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  sliding_up_panel: ^2.0.0+1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/marvel.png"

